

spring:
  application:
    name: services  
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      
  datasource:
    url : jdbc:mysql://localhost:3306/prafulla
    username : root
    password : password
    testWhileIdle : true
    validationQuery : SELECT 1
    max-active: 100
    max-idle: 50
    min-idle: 5
    driver-class-name: com.mysql.jdbc.Driver
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19880/eureka/
      
      
management:
  security:
    enabled: false

#spring:
#  application:
#     name : services
#  cloud:
#    config:
#      uri: http://localhost:8888
#      enabled: true